const AUTO_GENERATED_APPOINTMENT_NOTE_PREFIX = '客户信息未填写，系统自动创建'

export function isAutoGeneratedAppointmentNote(text?: string): boolean {
  return String(text || '').trim().startsWith(AUTO_GENERATED_APPOINTMENT_NOTE_PREFIX)
}

export function sanitizeAppointmentNotes(text?: string): string {
  const normalized = String(text || '').trim()
  if (!normalized) return ''
  if (isAutoGeneratedAppointmentNote(normalized)) return ''
  return normalized
}
